### ISSUE TITLE
Use snake_case for functions, methods, variables, and attribute names

### ISSUE THREAD

**Issue by jooyoungseo** [uiuc-ischool-accessible-computing-lab/py_maidr#2]
In Python, the recommended best practices for naming conventions are outlined in PEP 8, the Python community's official style guide.

Only use CamelCase for class names; otherwise, use snake_case for functions, methods, variables, and attributes' names.

**Comment by SaaiVenkat** [comment]
@jooyoungseo , I think we can close this issue now
